In [1]:
import tensorflow as tf
import os

In [2]:
from transformers import BertTokenizer, TFBertModel,BertConfig,TFBertForSequenceClassification

In [3]:
pt_base_model_path = "/Users/qianlai/Documents/_model/chinese_wwm_ext_pytorch"
tf_base_model_path = "/Users/qianlai/Documents/_model/chinese_L-12_H-768_A-12"

In [4]:

#         self.config = BertConfig.from_pretrained(os.path.join(self.model_path, "config.json"),
#                                                  num_labels=len(self.label_map))
#         self.tokenizer = BertTokenizer.from_pretrained("./")
#         self.model = TFBertForSequenceClassification.from_pretrained(self.model_path, config=self.config,
#                                                                      from_pt=self.from_pt_model)

In [5]:
config = BertConfig.from_pretrained(os.path.join(tf_base_model_path, "bert_config.json"),return_dict=True)


In [6]:
tokenizer = BertTokenizer.from_pretrained(tf_base_model_path)

In [7]:
model = TFBertModel.from_pretrained(pt_base_model_path,config=config,from_pt=True,trainable=False)

In [8]:
len(model.trainable_variables),len(model.variables)

(0, 199)

In [10]:
inputs = tokenizer.encode_plus("Hello, my dog is cute","dog is cute", return_tensors="tf",max_length=5,truncation=True)
inputs

{'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[  101,  8701,   102, 13030,   102]], dtype=int32)>,
 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 1, 1]], dtype=int32)>,
 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>}

In [24]:
res = model(inputs)
len(res)

2

In [25]:
res

(<tf.Tensor: shape=(1, 5, 768), dtype=float32, numpy=
 array([[[ 0.15142772,  0.16119553,  0.2958805 , ...,  0.4763003 ,
          -0.8964964 , -0.1023785 ],
         [ 0.10789293,  0.2606493 ,  0.61192864, ...,  0.01749855,
           0.15203723, -0.05980036],
         [ 0.18472797, -0.00390526,  0.18372674, ..., -0.23108403,
          -0.44938   ,  0.12237545],
         [ 0.20400985,  0.0733337 , -0.09181651, ...,  0.12772055,
          -0.4032764 ,  0.04381165],
         [ 0.18472801, -0.00390526,  0.18372673, ..., -0.23108399,
          -0.44938007,  0.12237544]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[ 0.99994826,  0.96286684,  1.        ,  0.95776075,  0.939037  ,
          0.23564488,  0.22715634, -0.9294734 ,  0.99731815, -0.99978876,
          1.        ,  0.9999997 ,  0.35612896, -0.6595206 ,  0.99994475,
         -0.9999964 , -0.8786965 ,  0.879491  ,  0.98761964, -0.243233  ,
          0.99116665, -0.9998822 , -0.04692547, -0.98878086,

In [26]:
a = res[0]
b=res[1]


In [27]:
a

<tf.Tensor: shape=(1, 5, 768), dtype=float32, numpy=
array([[[ 0.15142772,  0.16119553,  0.2958805 , ...,  0.4763003 ,
         -0.8964964 , -0.1023785 ],
        [ 0.10789293,  0.2606493 ,  0.61192864, ...,  0.01749855,
          0.15203723, -0.05980036],
        [ 0.18472797, -0.00390526,  0.18372674, ..., -0.23108403,
         -0.44938   ,  0.12237545],
        [ 0.20400985,  0.0733337 , -0.09181651, ...,  0.12772055,
         -0.4032764 ,  0.04381165],
        [ 0.18472801, -0.00390526,  0.18372673, ..., -0.23108399,
         -0.44938007,  0.12237544]]], dtype=float32)>

In [28]:
b

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 0.99994826,  0.96286684,  1.        ,  0.95776075,  0.939037  ,
         0.23564488,  0.22715634, -0.9294734 ,  0.99731815, -0.99978876,
         1.        ,  0.9999997 ,  0.35612896, -0.6595206 ,  0.99994475,
        -0.9999964 , -0.8786965 ,  0.879491  ,  0.98761964, -0.243233  ,
         0.99116665, -0.9998822 , -0.04692547, -0.98878086,  0.6396418 ,
         0.99990803,  0.99267447,  0.02039427, -0.9696231 ,  0.9999089 ,
         0.97346014,  0.99990314,  0.8573883 , -0.93381   , -0.99966276,
         0.7244423 ,  0.56286806,  0.9990853 ,  0.87983453, -0.19363138,
        -0.99710447, -0.94803834, -0.08368626, -0.9999784 , -0.7952221 ,
         0.96304893, -1.        , -0.99978393, -0.75368696,  0.96322423,
        -0.99548024, -0.99986225,  0.9966489 , -0.989801  , -0.6023406 ,
         0.979996  , -0.99985254,  0.9902699 ,  1.        ,  0.96046233,
         0.9998813 , -0.98080146,  0.19472668, -0.99993867,  0.9999912 ,
 

In [29]:
from transformers.modeling_tf_bert import TFBertLayer

In [30]:
bl = TFBertLayer(config)
bl

In [31]:
def make_extended_attention_mask(attention_mask):
    extended_attention_mask = attention_mask[:, tf.newaxis, tf.newaxis, :]
    extended_attention_mask = tf.cast(extended_attention_mask, tf.float32)
    extended_attention_mask = (1.0 - extended_attention_mask) * -10000.0
    return extended_attention_mask

In [32]:
extended_attention_mask = make_extended_attention_mask(inputs["attention_mask"])
extended_attention_mask

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[-0., -0., -0., -0., -0.]]]], dtype=float32)>

In [33]:
bl([a,extended_attention_mask,None],training=False)

(<tf.Tensor: shape=(1, 5, 768), dtype=float32, numpy=
 array([[[ 1.85800388e-01,  4.70507264e-01,  1.03713945e-04, ...,
           1.12904084e+00, -1.34059262e+00, -1.62133619e-01],
         [ 1.73023954e-01,  2.19356254e-01,  6.07259452e-01, ...,
           4.87740785e-01,  3.55566114e-01,  3.35050821e-01],
         [ 2.43497923e-01, -1.94329754e-01,  1.61229409e-02, ...,
          -1.77323163e-01, -7.34378755e-01,  5.25216460e-01],
         [ 2.17829242e-01,  1.27088219e-01, -8.33426476e-01, ...,
           3.64794731e-01, -4.93381470e-01,  4.48629081e-01],
         [ 2.43497789e-01, -1.94329858e-01,  1.61229596e-02, ...,
          -1.77323043e-01, -7.34379053e-01,  5.25216460e-01]]],
       dtype=float32)>,)