In [1]:
import tensorflow as tf
import os

In [2]:
from transformers import BertTokenizer, TFBertModel,BertConfig,TFBertForSequenceClassification

In [3]:
pt_base_model_path = "/Users/qianlai/Documents/_model/chinese_wwm_ext_pytorch"
tf_base_model_path = "/Users/qianlai/Documents/_model/chinese_L-12_H-768_A-12"

In [4]:

#         self.config = BertConfig.from_pretrained(os.path.join(self.model_path, "config.json"),
#                                                  num_labels=len(self.label_map))
#         self.tokenizer = BertTokenizer.from_pretrained("./")
#         self.model = TFBertForSequenceClassification.from_pretrained(self.model_path, config=self.config,
#                                                                      from_pt=self.from_pt_model)

In [5]:
config = BertConfig.from_pretrained(os.path.join(tf_base_model_path, "bert_config.json"))

In [6]:
tokenizer = BertTokenizer.from_pretrained(tf_base_model_path)

In [7]:
model = TFBertModel.from_pretrained(pt_base_model_path,config=config,from_pt=True,trainable=False)

All PyTorch model weights were used when initializing TFBertModel.

Some weights or buffers of the PyTorch model TFBertModel were not initialized from the TF 2.0 model and are newly initialized: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [8]:
len(model.trainable_variables),len(model.variables)

(0, 199)

In [18]:
inputs = tokenizer("Hello, my dog is cute","dog is cute", return_tensors="tf",max_length=5,truncation=True)
inputs

We need to remove 9 to truncate the inputbut the first sequence has a length 7. Please select another truncation strategy than TruncationStrategy.ONLY_FIRST, for instance 'longest_first' or 'only_second'.


{'input_ids': <tf.Tensor: shape=(1, 14), dtype=int32, numpy=
array([[  101,  8701,   117,  8422, 13030,  8310, 12322,  8154,   102,
        13030,  8310, 12322,  8154,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 14), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 14), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [19]:
text_a = "aaabb"
text_a

'aaabb'

In [73]:
res = model(inputs)

In [75]:
res

(<tf.Tensor: shape=(1, 9, 768), dtype=float32, numpy=
 array([[[-0.04025765,  0.02388757, -0.05523985, ...,  0.6597424 ,
          -0.6544312 , -0.26902568],
         [-0.12083986, -0.15467511,  0.7334155 , ...,  0.43884754,
           0.3165696 , -0.04993318],
         [-0.14061227, -0.69330525, -0.02921246, ...,  0.6728156 ,
           0.26200506, -0.02552088],
         ...,
         [-0.03988144,  0.5617645 ,  0.03748467, ...,  0.01448853,
           0.3784796 ,  0.08753122],
         [ 0.20831151, -0.08341092,  0.01874394, ...,  0.03371964,
           0.12051222, -0.17826055],
         [-0.01854608, -0.07565595,  0.33008647, ..., -0.2644417 ,
          -0.15177648, -0.10320424]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[ 0.99997205,  0.9910924 ,  0.9999966 ,  0.90741515,  0.935806  ,
          0.6709215 ,  0.12565446, -0.89365345,  0.99718523, -0.9992107 ,
          0.9999993 ,  0.99999416,  0.6852021 , -0.7103552 ,  0.9996556 ,
         -0.9999

In [76]:
a = res[0]
b=res[1]


In [77]:
a

<tf.Tensor: shape=(1, 9, 768), dtype=float32, numpy=
array([[[-0.04025765,  0.02388757, -0.05523985, ...,  0.6597424 ,
         -0.6544312 , -0.26902568],
        [-0.12083986, -0.15467511,  0.7334155 , ...,  0.43884754,
          0.3165696 , -0.04993318],
        [-0.14061227, -0.69330525, -0.02921246, ...,  0.6728156 ,
          0.26200506, -0.02552088],
        ...,
        [-0.03988144,  0.5617645 ,  0.03748467, ...,  0.01448853,
          0.3784796 ,  0.08753122],
        [ 0.20831151, -0.08341092,  0.01874394, ...,  0.03371964,
          0.12051222, -0.17826055],
        [-0.01854608, -0.07565595,  0.33008647, ..., -0.2644417 ,
         -0.15177648, -0.10320424]]], dtype=float32)>

In [78]:
b

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 0.99997205,  0.9910924 ,  0.9999966 ,  0.90741515,  0.935806  ,
         0.6709215 ,  0.12565446, -0.89365345,  0.99718523, -0.9992107 ,
         0.9999993 ,  0.99999416,  0.6852021 , -0.7103552 ,  0.9996556 ,
        -0.99998087, -0.9510721 ,  0.221149  ,  0.9842629 , -0.40262038,
         0.9969561 , -0.99952483, -0.46739644, -0.95168877,  0.71274227,
         0.9996717 ,  0.9818689 , -0.12803006, -0.9687859 ,  0.9996081 ,
         0.9680986 ,  0.9995757 ,  0.27229136, -0.8691227 , -0.9990318 ,
         0.82718766,  0.5834861 ,  0.99279815,  0.8957944 ,  0.16245057,
        -0.9791176 , -0.93927515, -0.71490115, -0.9999128 , -0.6603242 ,
         0.9760367 , -1.        , -0.99896157, -0.46774316,  0.9822921 ,
        -0.9887926 , -0.9993967 ,  0.99369913, -0.9903231 , -0.940849  ,
         0.978842  , -0.9997007 ,  0.9885831 ,  1.        ,  0.98132885,
         0.99974275, -0.9605996 ,  0.14137605, -0.9998007 ,  0.9999296 ,
 

In [55]:
import numpy as np
def convert_to_samples(value_span_lis, context, max_len):
    samples = []
    if not context:
        return samples
    for span in value_span_lis:
        begin = span[0]
        end = span[1]
        if begin >= end or end > len(context) or begin < 0:
            print("error span: %s->%s" % (begin, end))
            continue
        # trunction
        if end - begin > (max_len - 3) // 2 - 2:
            end = begin + (max_len - 3) // 2 - 2
        cut_context = context
        i=0
        if len(context) + (end - begin) > max_len - 3 - 2:
            # cut context
            i = begin
            j = end
            while (j - i) + (end - begin) < max_len - 3 - 2:
                if i > 0:
                    i -= 1
                if j < len(context):
                    j += 1
            cut_context = context[i:j]

        begin_offset = begin-(i-0)
        end_offset = end-(i-0)
            # 加点扰动
        left_disturbance = 0
        right_disturbance = 0
        if True:
            left_disturbance = np.random.choice([0, 1, 2], p=[0.5, 0.3, 0.2])
            right_disturbance = np.random.choice([0, 1, 2], p=[0.5, 0.3, 0.2])
        if begin_offset - left_disturbance >= 0:
            begin_offset = begin_offset - left_disturbance
        if end_offset + right_disturbance <= len(cut_context):
            end_offset = end_offset + right_disturbance
        
   

        text_a = cut_context[begin_offset:end_offset]
        text_b = cut_context[:begin_offset] + "【" + text_a + "】" + cut_context[end_offset:]

        tmp = {}
        tmp["text_a"] = text_a
        tmp["text_b"] = text_b
        tmp["span"] = (begin_offset, end_offset)
        samples.append(tmp)
    return samples

In [72]:
convert_to_samples([(0,2),(5,7),(8,17)],"一二三四五六七一二三四五六七一二三四五六七一二三四五六七",max_len=15)

[{'text_a': '一二三', 'text_b': '【一二三】四五六七一', 'span': (0, 3)},
 {'text_a': '六七', 'text_b': '三四五【六七】一二三', 'span': (3, 5)},
 {'text_a': '一二三四五六', 'text_b': '【一二三四五六】', 'span': (0, 6)}]

In [74]:
tokenizer("【一二】")

{'input_ids': [101, 523, 671, 753, 524, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1]}