In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

import numpy as np
import pandas as pd

In [57]:

a=tf.cast([[[1,1,1],[2,2,2]]],dtype=tf.float32)
a

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [2., 2., 2.]]], dtype=float32)>

In [58]:
g = tf.keras.layers.GRU(3, activation=None, return_sequences=True, use_bias=False,
                                    kernel_initializer = tf.keras.initializers.Ones())

In [59]:
g(a)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0.1422776 , 0.1422776 , 0.1422776 ],
        [0.15587354, 0.15737432, 0.15581338]]], dtype=float32)>

In [60]:
gb = tf.keras.layers.GRU(3, activation=None, return_sequences=True,use_bias=False,
                                    kernel_initializer = tf.keras.initializers.Ones(),go_backwards=True)

In [61]:
gb(a)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0.01483548, 0.01483548, 0.01483548],
        [0.15598507, 0.15474457, 0.15729752]]], dtype=float32)>

In [62]:
lay=tf.keras.layers.Bidirectional(g)

In [64]:
lay(a)

<tf.Tensor: shape=(1, 2, 6), dtype=float32, numpy=
array([[[0.1422776 , 0.1422776 , 0.1422776 , 0.15682167, 0.15809436,
         0.1565213 ],
        [0.15895668, 0.15598838, 0.15772335, 0.01483548, 0.01483548,
         0.01483548]]], dtype=float32)>